# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 110)
        MainWindow.setMinimumSize(QtCore.QSize(351, 110))
        MainWindow.setMaximumSize(QtCore.QSize(351, 110))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 41, 17))
        self.label.setObjectName("label")
        self.btnPath = QtWidgets.QToolButton(self.centralwidget)
        self.btnPath.setGeometry(QtCore.QRect(316, 9, 26, 24))
        self.btnPath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnPath.setObjectName("btnPath")
        self.btnOrganizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnOrganizar.setGeometry(QtCore.QRect(9, 40, 331, 31))
        self.btnOrganizar.setObjectName("btnOrganizar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 143, 21))
        self.label_2.setMaximumSize(QtCore.QSize(155, 100))
        self.label_2.setObjectName("label_2")
        self.inputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPath.setGeometry(QtCore.QRect(59, 9, 251, 25))
        self.inputPath.setObjectName("inputPath")
        self.nMusicasOrg = QtWidgets.QLineEdit(self.centralwidget)
        self.nMusicasOrg.setGeometry(QtCore.QRect(160, 80, 181, 25))
        self.nMusicasOrg.setMaximumSize(QtCore.QSize(190, 100))
        self.nMusicasOrg.setMouseTracking(False)
        self.nMusicasOrg.setObjectName("nMusicasOrg")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music Organizer"))
        self.label.setText(_translate("MainWindow", "Pasta:"))
        self.btnPath.setText(_translate("MainWindow", "..."))
        self.btnOrganizar.setText(_translate(
            "MainWindow", "Organizar Musicas"))
        self.label_2.setText(_translate(
            "MainWindow", "Total de Musicas Org.:"))
